### ISSUE TITLE
AssertionError: Run hello/net/run.py to report an error

### ISSUE THREAD

**Issue by pth2000** [byllyfish/finsy#395] opened 2024-01-02 11:43 UTC
When I try to execute `run.py`, it returns the following error:

```python
pth@ubuntu:~/Workspace/finsy_test/finsy-master/examples/hello$ ./net/run.py 
Traceback (most recent call last):
  File "/home/pth/Workspace/finsy_test/finsy-master/examples/hello/./net/run.py", line 3, in <module>
    from finsy.test import demonet as dn
  File "/home/pth/.local/lib/python3.10/site-packages/finsy/test/demonet.py", line 458, in <module>
    assert _LOCAL_P4SWITCH_PY.exists()
AssertionError
```

I have installed the `mininet` and `p4c` environments in Ubuntu20.

**Comment by byllyfish** [comment] 2024-01-02 19:58
Thanks for the report. The problem is that I did not include the `p4switch.py` file in the package.  I usually run the example tests using a repo clone, so I missed this.

Try running `PYTHONPATH=../.. ./net/run.py`

This will use the finsy package from finsy-master instead of the installed one. The relative link to p4switch.py should now work. I will fix the relative path issue in a future release.

**Comment by pth2000** [comment] 2024-01-03 03:40
Thank you for your reply, which is very useful!

However, I encountered some new problems:

```python
pth@ubuntu:~/Workspace/finsy_test/finsy-master/examples/hello$ PYTHONPATH=../.. python3.10 ./net/run.py
--------------------------------------------------------------------------------
Caught exception. Cleaning up...

TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
--------------------------------------------------------------------------------
rm: 无法删除 '/tmp/c0.log': 不允许的操作
ovs-vsctl: unix:/var/run/openvswitch/db.sock: database connection failed (Permission denied)
ovs-vsctl: unix:/var/run/openvswitch/db.sock: database connection failed (Permission denied)
```

Try to use `sudo`:

```python
pth@ubuntu:~/Workspace/finsy_test/finsy-master/examples/hello$ sudo PYTHONPATH=../.. python3.10 ./net/run.py
Traceback (most recent call last):
  File "/home/pth/Workspace/finsy_test/finsy-master/examples/hello/./net/run.py", line 21, in <module>
    dn.main(DEMONET)
  File "/home/pth/Workspace/finsy_test/finsy-master/finsy/test/demonet.py", line 592, in main
    run(config)
  File "/home/pth/Workspace/finsy_test/finsy-master/finsy/test/demonet.py", line 554, in run
    asyncio.run(_main())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/pth/Workspace/finsy_test/finsy-master/finsy/test/demonet.py", line 552, in _main
    await net.run_interactively()
  File "/home/pth/Workspace/finsy_test/finsy-master/finsy/test/demonet.py", line 410, in run_interactively
    cmd = await self._mininet_command()
  File "/home/pth/Workspace/finsy_test/finsy-master/finsy/test/demonet.py", line 429, in _mininet_command
    self._config_file.write_text(self.config.to_json(remote=False))
  File "/usr/local/lib/python3.10/pathlib.py", line 1154, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors, newline=newline) as f:
  File "/usr/local/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
PermissionError: [Errno 13] Permission denied: '/tmp/demonet_config.json'
```

I'm not sure if this problem is related to my system environment.

**Comment by byllyfish** [comment] 2024-01-04 04:25
It looks like your /tmp directory is not writable due to some kind of mandatory access control. This may also cause problems running mininet.

The main purpose of the ./net/run.py scripts is to run mininet tests in a container. However, if you have mininet installed locally (the "mn" command is in the path), the script sees that and tries to run mininet locally. This is causing all kinds of problems for you.

Until I can re-work some things, I suggest that you rename the "mn" command to "mnx" or something else. This will force the run script to use the docker/podman mechanism instead. You do not need to have mininet or p4c installed; everything needed is on the docker image.

**Comment by byllyfish** [comment] 2024-01-04 05:24
I have just pushed a fix to main that will eliminate the need to rename "mn" or uninstall mininet.

**Comment by pth2000** [comment] 2024-01-04 12:45
I tried to switch to another virtual machine with docker installed but no mininet installed. I had a problem with docker permissions but luckily I solved it by adding a user group.

Now I can run the "hello" example program, thanks for your reply!

**Closed** 2024-01-06 16:10 UTC
